//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkolaProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skola
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skola()
        {
            this.tblDjelatniks = new HashSet<Djelatnik>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Mjesto { get; set; }
        public string Adresa { get; set; }
        public string WebStranica { get; set; }
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Djelatnik> tblDjelatniks { get; set; }
    }
}
